# Restricting deployments and components scrapped
alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: ""
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

# Configuring Prometheus and Grafana for them to be reachable from outside
prometheus:
  serviceAccount:
    create: false
    name: prometheus-privileged
  service:
    type: NodePort
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        component: beeant-webapp
grafana:
  service: 
    type: NodePort
  securityContext:
    runAsUser: 1000
  rbac:
    useExistingRole: cluster-admin
  persistence:
    enabled: true

# Config only for prometheus-community/prometheus
# server:
#   useExistingClusterRoleName: admin
#   namespaces:
#     - default
#   persistentVolume:
#     enabled: false
#   statefulSet:
#     enabled: true
#   service:
#     type: NodePort
#     servicePort: 9090